# Bitbucket Pipelines Calldorado Template to build, test and deploy our SDKs.

# This template contains 3 parallel steps to build Android application, run Android code scanning tool and run unit tests.

# The CDO Docker image has Android SDK 30 with pre-installed build tools and emulator image.
# Note: This docker image is created and maintained @Mirza and @Peter. For more details see: https://hub.docker.com/repository/docker/calldorado/sdk-repo
image:
  name: calldorado/sdk-repo:container-v1
  username: $DOCKER_HUB_USERNAME
  password: $DOCKER_HUB_PASSWORD
  email: $DOCKER_HUB_EMAIL

pipelines:
  branches:
    master:
      - parallel:
          - step:
              name: Android Release SDK
              caches: # caching speed up subsequent execution https://support.atlassian.com/bitbucket-cloud/docs/cache-dependencies/
                - gradle
                - docker
              script:
                - ./gradlew clean :preonboarding:assembleRelease --stacktrace --info
                - ./gradlew :preonboarding:publish -s -i
              services:
                - docker
          - step:           # step to run lint (Android code scanning tool)
              name: Lint
              caches:       # caching speed up subsequent execution https://support.atlassian.com/bitbucket-cloud/docs/cache-dependencies/
                - gradle
              script:
                - ./gradlew lint
              artifacts:
                - preonboarding/build/reports/**        # artifacts are files that are produced by a step https://support.atlassian.com/bitbucket-cloud/docs/use-artifacts-in-steps/
          - step:
              name: Unit Tests
              caches:
                - gradle    # caching speed up subsequent execution https://support.atlassian.com/bitbucket-cloud/docs/cache-dependencies/
              script:
                - ./gradlew testDebugUnitTest # test reporting is automatically enabled https://support.atlassian.com/bitbucket-cloud/docs/test-reporting-in-pipelines/
