-keep interface com.calldorado.preonboarding.** { *; }
-keep class com.calldorado.preonboarding.** { *; }
-keep class com.calldorado.preonboarding.**$* { *; }
-dontwarn com.calldorado.preonboarding.**
-keep class kotlin.Unit { *; }